version: '3.8'

services:
  app:
    container_name: gym-community-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gym_community
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - gym-network

  postgres:
    container_name: gym-community-postgres
    image: postgres:15
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=gym_community
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  postgres-data: